from crawlerBot_pack_SCI_2019.crawlerbots.kakaostoryCrawlerBot import kakao_story_crawler_start
from crawlerBot_pack_SCI_2019.crawlerbots.facebookCrawlerBot import facebook_crawler_start

facebook_crawler_start()
kakao_story_crawler_start()